### ISSUE TITLE
Allow exporting to video/gifs

### ISSUE THREAD

**Issue by Alejandro-Sosa** [gliscowo/isometric-renders#3]
Would be nice to be able to export a video of a render with animations or enchantment glint for example.

**Comment by Cahseww** [comment]
this would be the best day of my life

**Comment by gliscowo** [comment]
Implemented in [0.3.0](https://modrinth.com/mod/isometric-renders/version/F90awBdP) - @Cahseww it appears the best day of your life is today
Cheers
